admin_panel/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, re_path, url
from django.shortcuts import redirect
from clients import views as client
from django.conf import settings

urlpatterns = [
    path('', lambda request: redirect('admin/', permanent=True)),
    path('costStatements/', include('costStatements.urls')),  # it makes it public ?
    path('registration/', include('clients.urls')),
    path('litigation/', include('litigations.urls')),
    url(r'^attachments/', include('attachments.urls', namespace='attachments')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        client.activate, name='activate'),
    # path('media/documents/<slug:title>')
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

clients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:lang>', views.register, name='register'),
]

clients/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

phone_prefixes = (
    ('+39', '+39'),
    ('+355', '+355'),
    ('+44', '+44'),
    ('+43', '+43'),
    ('+32', '+32'),
    ('+359', '+359'),
    ('+357', '+357'),
    ('+420', '+420'),
    ('+45', '+45'),
    ('+372', '+372'),
    ('+358', '+358'),
    ('+33', '+33'),
    ('+49', '+49'),
    ('+49', '+49'),
    ('+30', '+30'),
    ('+36', '+36'),
    ('+354', '+354'),
    ('+353', '+353'),
    ('+371', '+371'),
    ('+423', '+423'),
    ('+370', '+370'),
    ('+352', '+352'),
    ('+356', '+356'),
    ('+31', '+31'),
    ('+47', '+47'),
    ('+48', '+48'),
    ('+351', '+351'),
    ('+40', '+40'),
    ('+421', '+421'),
    ('+421', '+421'),
    ('+386', '+386'),
    ('+34', '+34'),
    ('+46', '+46'),
    ('+383', '+383'),
    ('+389', '+389'),
    ('+382', '+382'),
    ('+381', '+381'),
    ('+381', '+381'),
    ('+41', '+41'),
    ('+90', '+90'),
    ('+380', '+380'),
)

def increment_customer_number():
    code = 'C' + '001'
    last_contact = Customer.objects.all().order_by('id').last()
    if not last_contact:
        return code
    last_code = last_contact.code
    sequence = int(last_code[1:]) + 1
    code = 'C' + str(sequence).zfill(3)
    return code


class Customer(models.Model):
    code = models.CharField(_("Code"), max_length=20, unique=True,
                            default=increment_customer_number, )  # editable=False
    hubspot_card = models.URLField(verbose_name=_("Hubspot Card"), blank=True, null=True, max_length=7000)
    # fill name from company_name if company or name surname if individual
    name = models.CharField(_("Name"), max_length=100, blank=True, null=True)

    fiscal_code = models.CharField(_("Fiscal Code"), max_length=100, blank=True, null=True)
    vat_number = models.CharField(_("Vat Number"), max_length=100, blank=True, null=True)

    company_name = models.CharField(_("Company Name"), max_length=100, blank=True, null=True)
    # TODO: possibility to add more than one contacts per company - contacts field m2m below
    contact_person = models.CharField(_("Contact Person"), max_length=100, blank=True, null=True)
    role = models.CharField(_("Role"), max_length=100, blank=True, null=True)

    first_name = models.CharField(_("Name"), max_length=100, blank=True, null=True)
    last_name = models.CharField(_("Last Name"), max_length=100, blank=True, null=True)

    email = models.EmailField(_("e-mail"), null=True, unique=True)
    phone_prefix = models.CharField(max_length=100,
                                    choices=phone_prefixes,
                                    default=None,
                                    null=True)
    phone = models.IntegerField(_("Phone"), blank=True, null=True)
    mobile_prefix = models.CharField(max_length=100,
                                    choices=phone_prefixes,
                                    default=None,
                                    null=True)
    mobile = models.IntegerField(_("Mobile"), blank=True, null=True)
    gender = models.CharField(_("Gender"),
                              choices=((None, ''),
                                       ('F', 'Femmina'),
                                       ('M', 'Maschio')), max_length=10, default=None, blank=True, null=True)
    birthday = models.DateField(_("Birthday"), null=True, blank=True)
    birthplace = models.CharField(_("Birth-place"), max_length=100, blank=True, null=True)

    street = models.CharField(_("Street"), max_length=256, null=True, )
    # TODO: city: add entity? If so, should be preconfigured for public usage
    city = models.CharField(_("City"), max_length=256, null=True, )
    post_number = models.CharField(_("Post Number"), max_length=100, null=True)

    customer_type = models.CharField(_("Customer Type"),
                                     choices=(('individual', 'Individuo'),
                                              ('company', 'Azienda'),), max_length=16, default='individual', null=True)
    contacts = models.ManyToManyField('self', verbose_name=_('contacts'), blank=True, )
    is_customer = models.BooleanField(_("Is Customer"), db_index=True, default=False, )
    is_active = models.BooleanField(_("Is Active"), db_index=True, default=False, )
    origin = models.CharField(_("origin"), choices=(
        ('internal', 'interno'),
        ('web', 'web')), max_length=8, default='internal', blank=True, null=True)

    def __str__(self):
        return "[%s] %s" % (self.code, self.name)

    def __init__(self, *args, **kwargs):
        # TODO: filter to show only individuals in m2m contacts field
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        """ activate by default if contact is registered interally
        """
        if self.origin == 'internal':
            self.is_active = True
        super(Customer, self).save(*args, **kwargs)

    @property
    def name(self):
        name = self.company_name
        if self.customer_type == 'individual':
            name = ''.join([self.first_name or " ", ' ', self.last_name or " "])
        return name

    class Meta:
        db_table = "customer"
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

clients/views.py
from django.shortcuts import render, redirect
from notifications.mail import *
from .forms import ContactForm
from django.http import HttpResponse
from .tokens import contact_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.utils import translation
from django.utils.translation import gettext_lazy as _

registration_page = "index.html"


def register(request, lang):
    translation.activate(lang)
    form = ContactForm()

    # for key in form.fields:
        # form.fields[key].label = _(form.fields[key].label)

    if request.method == "POST":
        form = ContactForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            form.cleaned_data['origin'] = 'web'
            record = form.save()
            record.save()
            try:
                current_site = get_current_site(request)
                email_context = {
                    'id': record.id,
                    'name': record.name,
                    'code': record.code,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(record.pk)),
                    'token': contact_activation_token.make_token(record)
                }
                to_email = record.email
                # send email from notification module as subject configured
                send_email_template(
                    email=to_email, context=email_context,
                    notification_type='customer_registration',
                    notify_on="form_submit", request=request)
                request.session['message'] = "thank-you-registering"
                return redirect('/litigation/' + lang)
            except Exception as error:
                print("Print error: ", error)
                return HttpResponse(error)

    context = {"language": lang, 'form': form}
    return render(request, registration_page, context)


def activate(request, uidb64, token):
    """
        Contact activation
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        contact = Customer.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Customer.DoesNotExist):
        contact = None

    if contact is not None:
        contact.is_active = True
        contact.save()

        # START: SEND EMAIL ON CUSTOMER ACTIVATION
        # make context with record_id data dictionary
        data = Customer.objects.filter(id=contact.id).values()
        context = list(data)[0]  # from queryset -> [{}] -> {}
        # update context with name
        context['name'] = contact.name

        # check for scheduled e-mail notification on contact activation
        send_email_template(
            email=None, context=context, notification_type='customer_registration',
            notify_on="url_click", request=request
        )
        # END
        return HttpResponse(_('Data Verification Thank You'))
    else:
        return HttpResponse(_('Invalid Link'))

clients/templates/contact_confirmation_email.html
{% autoescape off %}
Hi {{ contact.name }},

Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

{% endautoescape %}

clients/templates/index.html
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}

{% load material_form %}
{% load i18n %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% translate "registration" %}</title>

  <!-- Compiled and minified JavaScript -->
  <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
  <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="module" src="{% static 'admin/js/contact_type.js' %}"></script>


  <!-- Temporary!!
    Added registration static file here,
    registration.js as it is not loaded in /litigation form from its index html page
  -->
<!--  <script src="{% static 'admin/js/litigation.js' %}"></script>-->


  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script>
    $(document).ready(function(){
      $('select').formSelect();
    });
  </script>

  <!-- Compiled and minified CSS -->
  <meta name = "viewport" content = "width = device-width, initial-scale = 1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel = "stylesheet"
       href = "https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel = "stylesheet" href = "{% static 'admin/css/clients.css' %}">

</head>

<div class="container"  style="width:80%;">
    <div class="col-lg-6" style="float:none;margin:auto;">
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages%}

        <div class="custom-dropdown">
          {% if var1 %}
            {{ var1 }}
          {% endif %}
          <div class="custom-toggle-dropdown" onclick="toggleLanguageDropDown()">
            {% for lang in languages %}
              {% if lang.code == language %}
                {{ lang.name }}
              {% endif %}
            {% endfor %}
          </div>
            <div class="custom-dropdown-content" id="languageDropdown">
              {% for lang in languages %}
                <div>
                  <a href="https://projects.gridcoding.com/defynd/registration/{{lang.code}}" class="custom-dropdown-option" onclick="toggleLanguageDropDown()">
                    {{lang.name}}
                  </a>
                </div>
              {% endfor %}

            </div>
        </div>


        <form method="POST">
            {% csrf_token %}

            {% form form=form %}
            {% endform %}

            <button type="submit" name="_submit" class="btn">{% translate "send" %}</button>
        </form>

        <!-- <script>
          $( function()
          { // TODO fix datepicket format
            $( "#id_birthday" ).datepicker({ dateFormat: 'dd/mm/yyyy' }).val();
            $("#datepicker").datepicker({ dateFormat: "dd/mm/yyyy" }).val();
          } );
        </script> -->
    </div>
</div>
<script>

  languageDropdownIsOpened = false;
      function toggleLanguageDropDown() {
        console.log("clicked!", languageDropdownIsOpened)
        const languageDropdown = document.getElementById("languageDropdown");
        if(languageDropdownIsOpened) {
            // close dropdown
            languageDropdown.style.display = "none";
        } else {
            languageDropdown.style.display = "block";
        }
        languageDropdownIsOpened = !languageDropdownIsOpened;
    }

</script>